Update APT prior to installing system dependencies
Builds consistently failed throughout the day with the following error:

```
Ign:1 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64
libcurl4-openssl-dev amd64 7.68.0-1ubuntu2.7
Err:1 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64
libcurl4-openssl-dev amd64 7.68.0-1ubuntu2.7
  404  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch
http://azure.archive.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4-openssl-dev_7.68.0-1ubuntu2.7_amd64.deb
404  Not Found [IP: 40.81.13.82 80]
E: Unable to fetch some archives, maybe run apt-get update or try with
--fix-missing?
Error: Process completed with exit code 100.
```

From searching the error, the solution is to run `apt-get update` first:

https://askubuntu.com/questions/519539/failed-to-fetch-http-security-ubuntu-com-ubuntu-pool-main-e-eglibc-libc-bin-2

https://github.com/r-lib/actions/issues/554